# Generated by Django 5.0.2 on 2024-02-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('e_id', models.CharField(max_length=64)),
                ('current_role', models.CharField(max_length=64)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('ctc', models.IntegerField()),
            ],
        ),
    ]
