# Generated by Django 5.0.2 on 2024-02-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
