# Generated by Django 5.0.2 on 2024-02-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='positions',
        ),
    ]
