# Generated by Django 5.0.2 on 2024-02-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_rename_departments_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
